import Providers from "../providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div style={{
      backgroundColor: "white",
      color: "black",
      fontFamily: "sans-serif",
      margin: 0,
      padding: 0,
      minHeight: "100vh",
    }}>
      {children}
    </div>
  );
}
