import Providers from "../providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body style={{
          backgroundColor: "white",
          color: "black",
          fontFamily: "sans-serif",
          margin: 0,
          padding: 0,
          height: "100vh",
        }}>{children}</body>
      </Providers>
    </html>
  );
}
